Separate bach_repository from bcpc to support unit-testing

diff --git a/cookbooks/bach_repository/templates/default/chef-install.sh.erb b/cookbooks/bach_repository/templates/default/chef-install.sh.erb
--- a/cookbooks/bach_repository/templates/default/chef-install.sh.erb
+++ b/cookbooks/bach_repository/templates/default/chef-install.sh.erb
@@ -21,13 +21,11 @@ else
 fi
 
 # Remove rubygems and install only our gemserver
-/opt/chef/embedded/bin/gem sources --add http://<%= node['bcpc']['bootstrap']['server'] %>/ || (echo "Failed to add local Gem repo")
+/opt/chef/embedded/bin/gem sources --add http://<%= node['bach']['repository']['gem_server'] %>/ || (echo "Failed to add local Gem repo")
 /opt/chef/embedded/bin/gem sources --remove http://rubygems.org/ || true
 /opt/chef/embedded/bin/gem sources --remove https://rubygems.org/ || true
-/opt/chef/embedded/bin/gem sources | grep -q "^http://<%= node['bcpc']['bootstrap']['server'] %>/$" || (echo "Failed to add bootstrap to gem sources")
-/opt/chef/embedded/bin/gem install faraday || (echo "Failed to install Faraday"; exit 1)
-/opt/chef/embedded/bin/gem install cluster_def || (echo "Failed to install cluster_def"; exit 1)
+/opt/chef/embedded/bin/gem sources | grep -q "^http://<%= node['bach']['repository']['gem_server'] %>/$" || (echo "Failed to add bootstrap to gem sources")
 
 # Update chef client configuration
 mkdir -p /etc/chef/client.d || (echo "Failed to create /etc/chef/client.d")
-echo "rubygems_url 'http://<%= node['bcpc']['bootstrap']['server'] %>/'" > /etc/chef/client.d/rubygems_url.rb || (echo "Failed to write rubygems_url file in /etc/chef/client.d")
+echo "rubygems_url 'http://<%= node['bach']['repository']['gem_server'] %>/'" > /etc/chef/client.d/rubygems_url.rb || (echo "Failed to write rubygems_url file in /etc/chef/client.d")
