Working chef-install.sh

diff --git a/cookbooks/bach_repository/templates/default/chef-install.sh.erb b/cookbooks/bach_repository/templates/default/chef-install.sh.erb
--- a/cookbooks/bach_repository/templates/default/chef-install.sh.erb
+++ b/cookbooks/bach_repository/templates/default/chef-install.sh.erb
@@ -26,13 +26,13 @@ if ! getent hosts <%= @chef_server_fqdn %>; then
 fi
 
 # Remove rubygems and install only our gemserver
-/opt/chef/embedded/bin/gem sources --add http://<%= node['bach']['repository']['gem_server'] %>/ || (echo "Failed to add local Gem repo")
+/opt/chef/embedded/bin/gem sources --add <%= node['bach']['repository']['gem_server'] %> || (echo "Failed to add local Gem repo")
 /opt/chef/embedded/bin/gem sources --remove http://rubygems.org/ || true
 /opt/chef/embedded/bin/gem sources --remove https://rubygems.org/ || true
-/opt/chef/embedded/bin/gem sources | grep -q "^http://<%= node['bach']['repository']['gem_server'] %>/$" || (echo "Failed to add bootstrap to gem sources")
+/opt/chef/embedded/bin/gem sources | grep -q "^<%= node['bach']['repository']['gem_server'] %>$" || (echo "Failed to add bootstrap to gem sources")
 # Stomp /etc/gemrc to not proxy our local Gem server
 echo 'http_proxy: :no_proxy' > /etc/gemrc
 
 # Update chef client configuration
 mkdir -p /etc/chef/client.d || (echo "Failed to create /etc/chef/client.d")
-echo "rubygems_url 'http://<%= node['bach']['repository']['gem_server'] %>/'" > /etc/chef/client.d/rubygems_url.rb || (echo "Failed to write rubygems_url file in /etc/chef/client.d")
+echo "rubygems_url '<%= node['bach']['repository']['gem_server'] %>'" > /etc/chef/client.d/rubygems_url.rb || (echo "Failed to write rubygems_url file in /etc/chef/client.d")
