In progress corrections post June re-base

diff --git a/cookbooks/bach_repository/templates/default/chef-install.sh.erb b/cookbooks/bach_repository/templates/default/chef-install.sh.erb
--- a/cookbooks/bach_repository/templates/default/chef-install.sh.erb
+++ b/cookbooks/bach_repository/templates/default/chef-install.sh.erb
@@ -25,17 +25,22 @@ if ! getent hosts <%= @chef_server_fqdn %>; then
   echo "<%= "#{@chef_server_ip}\t#{@chef_server_fqdn}" %>" >> /etc/hosts
 fi
 
-# Remove rubygems and install only our gemserver
-/opt/chef/embedded/bin/gem sources --add <%= node['bach']['repository']['gem_server'] %> || (echo "Failed to add local Gem repo")
-/opt/chef/embedded/bin/gem sources --remove http://rubygems.org/ || true
-/opt/chef/embedded/bin/gem sources --remove https://rubygems.org/ || true
-/opt/chef/embedded/bin/gem sources | grep -q "^<%= node['bach']['repository']['gem_server'] %>$" || (echo "Failed to add bootstrap to gem sources")
 # Stomp /etc/gemrc to not proxy our local Gem server
-echo 'http_proxy: :no_proxy' > /etc/gemrc
+# Remove rubygems and install only our gemserver source
+cat > /etc/gemrc << EOH
+:sources:
+- <%= node['bach']['repository']['gem_server'] %>/
+EOH
 
+# Ensure the Chef gem/bundler know where to look too
+mkdir /opt/chef/embedded/etc
+ln -s /etc/gemrc /opt/chef/embedded/etc/gemrc
+
+export "RUBYGEMS_HOST=<%= node['bach']['repository']['gem_server'] %>"
+export "NO_PROXY=<%= node['chef_client']['config']['no_proxy'] %>"
 /opt/chef/embedded/bin/gem install faraday || (echo "Failed to install Faraday"; exit 1)
 /opt/chef/embedded/bin/gem install cluster_def || (echo "Failed to install cluster_def"; exit 1)
 
 # Update chef client configuration
 mkdir -p /etc/chef/client.d || (echo "Failed to create /etc/chef/client.d")
-echo "rubygems_url '<%= node['bach']['repository']['gem_server'] %>'" > /etc/chef/client.d/rubygems_url.rb || (echo "Failed to write rubygems_url file in /etc/chef/client.d")
+echo "rubygems_url '<%= node['bach']['repository']['gem_server'] %>'" > /etc/chef/client.d/rubygems_url.rb || (echo "Failed to write rubygems_url file in /etc/chef/client.d"; exit 1)
